package:
  name: conda-ui
  version: 1.0.0

build:
  number: {{ environ.get('BINSTAR_BUILD', 1) }}
  entry_points:
    - conda-ui = conda_ui:main

requirements:
  build:
    - python
    - distribute
    - setuptools

  run:
    - python
    - flask
    - werkzeug
    - conda

about:
  home: https://github.com/ContinuumIO/conda-ui
  license: MIT License
