package:
  name: conda-ui
  version: 0.1.1

build:
  number: {{ environ.get('BINSTAR_BUILD', 1) }}
  entry_points:
    - conda-ui = conda_ui:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - flask
    - conda
    - tornado
    - sockjs-tornado

app:
  entry: conda-ui
  icon: logo.png
  summary: Conda UI - Graphical Interface for Conda
  type: web

about:
  home: https://github.com/ContinuumIO/conda-ui
  license: BSD License
